Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.hostname = "kubeworker3"
  config.vm.network :private_network, ip: "192.168.56.33"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "2048",
      "--cpus", "1"
    ]
  end
end
