Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "kubemaster"
  config.vm.network :private_network, ip: "192.168.56.30"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "4096",
      "--cpus", "2"
    ]
  end
end
