# This file is to show how a secret can be created via yaml file, you do it via command line as well
# Secret data should not be committed to code repo
# secrets has to stored base64 encoded
# base64 encoding can be done via command line - echo -n 'admin' | base64
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  user: YWRtaW4=
  password: YWRtaW4xMjM=  